#' Step 2: Combine Parsed Data Files
#'
#' @param parsed_path Path to the directory containing the parsed files generated by `threader_parse()`.
#' @param combined_path Path to the directory where you want the combined data saved
#' @param spec_fpath Path to the `.yaml`-format spec file.
#' @param verbose Optional: If `TRUE`, prints additional debugging information.
#'
#' @return Output: a giant csv file with a row for *every* piece of data we have
#' @export
#'
#' @examples
#' combined_df <- threader_combine()
threader_combine <- function(parsed_path = NULL, combined_path = NULL,
                             spec_fpath = NULL, verbose = FALSE) {
  if (is.null(parsed_path)) {
    parsed_path <- demo_parsed_path()
  }
  if (is.null(combined_path)) {
    combined_path <- demo_combined_path()
  }
  if (is.null(spec_fpath)) {
    spec_fpath <- demo_spec_fpath()
  }
  # Parse spec
  spec <- .parse_spec_file(spec_fpath)
  # Get the varname from the spec
  grid_varname <- .spec_get_varname(spec)
  varname_glob <- file.path(parsed_path, "*.rds")
  if (verbose) { print(paste0("Checking for .rds files via ",varname_glob)) }
  parsed_fpaths <- Sys.glob(varname_glob)
  if (verbose) {
      print("parsed_fpaths:")
      print(parsed_fpaths)
  }
  # Remove combined.rds, if it already exists, just in case
  parsed_fpaths <- parsed_fpaths[!stringr::str_detect(parsed_fpaths, "combined.rds")]
  full_df <- dplyr::tibble()
  for (cur_fpath in parsed_fpaths) {
    cur_df <- readRDS(cur_fpath)
    full_df <- dplyr::bind_rows(full_df, cur_df)
  }
  csv_output_fpath <- file.path(combined_path, "all_entries.csv")
  readr::write_csv(full_df, csv_output_fpath)
  rds_output_fpath <- stringr::str_replace(csv_output_fpath, ".csv", ".rds")
  if (verbose) { print(paste0("Saving to ",rds_output_fpath)) }
  saveRDS(full_df, rds_output_fpath)
  return_env <- new.env()
  rlang::env_poke(return_env, "data", full_df)
  rlang::env_poke(return_env, "csv_fpath", csv_output_fpath)
  rlang::env_poke(return_env, "rds_fpath", rds_output_fpath)
  return(return_env)
}
